# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: jpeg-fun-indexer
networks:
- id: 84532
  start_block: 19042649
  contracts:
  - name: Marketplace
    address:
    - 0x01dA06dCAE5F1E49E4333473f1dDeA9DBC6D1FF7
    handler: src/EventHandlers.ts
    events:
    - event: AuctionBuffersUpdated(uint256 timeBuffer, uint256 bidBufferBps)
    - event: AuctionClosed(uint256 indexed listingId, address indexed closer, bool indexed cancelled, address auctionCreator, address winningBidder)
    - event: Initialized(uint8 version)
    - event: ListingAdded(uint256 indexed listingId, address indexed assetContract, address indexed lister, (uint256,address,address,uint256,uint256,uint256,uint256,address,uint256,uint256,uint8,uint8) listing)
    - event: ListingRemoved(uint256 indexed listingId, address indexed listingCreator)
    - event: ListingUpdated(uint256 indexed listingId, address indexed listingCreator, (uint256,address,address,uint256,uint256,uint256,uint256,address,uint256,uint256,uint8,uint8) listing)
    - event: NewOffer(uint256 indexed listingId, address indexed offeror, uint8 indexed listingType, uint256 quantityWanted, uint256 totalOfferAmount, address currency)
    - event: NewSale(uint256 indexed listingId, address indexed assetContract, address indexed lister, address buyer, uint256 quantityBought, uint256 totalPricePaid)
rollback_on_reorg: false
